// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMrzFJdId5AIMsJPrKdkLlbY3oEF7SFJc',
    appId: '1:424688717766:web:0e6e3218773ab544edacc7',
    messagingSenderId: '424688717766',
    projectId: 'confess-9cf0d',
    authDomain: 'confess-9cf0d.firebaseapp.com',
    storageBucket: 'confess-9cf0d.firebasestorage.app',
    measurementId: 'G-DVD1R0HBN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkiY9378Jlkh3sfw58P-4eyem0sEZU25A',
    appId: '1:424688717766:android:50acd88467e48327edacc7',
    messagingSenderId: '424688717766',
    projectId: 'confess-9cf0d',
    storageBucket: 'confess-9cf0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSMM2UVoCWoKFWR6w9K2y25-762GVWoag',
    appId: '1:424688717766:ios:19abe50c129dff15edacc7',
    messagingSenderId: '424688717766',
    projectId: 'confess-9cf0d',
    storageBucket: 'confess-9cf0d.firebasestorage.app',
    iosBundleId: 'com.confess.app.confessApp',
  );
}
